import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  backlog: [{type: 'autogenerated', dirName: 'backlog'}],

  comunicacao: [{type: 'autogenerated', dirName: 'comunicacao'}],

  disc: [{type: 'autogenerated', dirName: 'disc'}],



  pmc: [{type: 'autogenerated', dirName: 'pmc'}],

  team_topology: [{type: 'autogenerated', dirName: 'team_topology'}] 
};

export default sidebars;
